source "https://rubygems.org"

# Specify your gem's dependencies in pylon.gemspec.
gemspec

gem "faraday", "~> 1.10.4"
gem "json", "~> 2.0"

group :development do
  gem "rubocop-rake", "~> 0.7"
  gem "rubocop-rspec", "~> 3.0"
end
